### ISSUE TITLE
I'm a fan of yours.

### ISSUE THREAD

**Issue by subutuo** [loveRandy/vue-cli3.0-vueadmin#2]
![image](https://user-images.githubusercontent.com/26793124/53621524-1f281100-3c3a-11e9-927b-b7593f1a3331.png)

**Comment by loveRandy** [comment]
nice

**Comment by subutuo** [comment]
How did you study Vue?

**Comment by loveRandy** [comment]
from the studied movie book and the othe people who share the study data on the internet

**Comment by subutuo** [comment]
Do you mind if I ask you anything I don't know about Vue? Of course, after I've studied for myself.

**Comment by loveRandy** [comment]
Why not

**Comment by subutuo** [comment]
If you'll be my teacher, I'll draw you another picture.

**Comment by loveRandy** [comment]
what a beautiful picture,don't change it ;I like it

**Comment by subutuo** [comment]
good good
