### ISSUE TITLE
怎么修改成自己服务后台API接口的地址啊？

### ISSUE THREAD

**Issue by situmill** [loveRandy/vue-cli3.0-vueadmin#4]
程序build ,放到web服务器后 运行为http://xxx.xxx:8099/,  POST登录 http://xxx.xxx:8099/user/login , 但是API接口并不是8099,如何配置成非8099的API接口呢？vue新人一枚

**Comment by Kchengz** [comment]
> 程序构建，放到web服务器后运行为[http://xxx.xxx:8099/,POST](http://xxx.xxx:8099/)登录http://xxx.xxx:8099/user/login ,但是API接口并不是8099，如何配置成非8099的API接口呢？VUE新人一枚

你可以尝试修改[https://github.com/loveRandy/vue-cli3.0-vueadmin/blob/master/src/utils/request.js](https://github.com/loveRandy/vue-cli3.0-vueadmin/blob/master/src/utils/request.js)这里面的baseUrl的地址及端口号
